### ISSUE TITLE
Variable type shadows built-in function

### ISSUE THREAD

**Issue by joe-arriaga** [danieldupriest/reimbursinator#73]
In `backend/models.py`:
`class Field(models.Model):
     .
     .
     .
     type = models.CharField(max_length=128)
`
`type` shadows the built-in `type()` function,
Change to field_type, data_type, etc. ?

**Comment by danieldupriest** [comment]
So this basically means that we can't use the `type()` function, but it still does work otherwise? We'll need to coordinate a patch on the back and front ends at the same time to change it. I recommend `field_type`.

**Comment by rupikad** [comment]
Fixed

**Comment by rupikad** [comment]
fixed
